# -*- coding: utf-8 -*-
"""CaseStudy(OOPs).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n_HG1jz0hT_IE8on-M0URlKEGD9ZNamj
"""

#Q1
class Employee:
  def __init__(self,employee_name,employee_salary):
    self.employee_name=employee_name
    self.employee_salary=employee_salary
  def __str__(self,employee_name,employee_salary):  
    print("Name:",self.employee_name)
    print("Salary:",self.employee_salary)

obj=Employee("sreehari",10)
obj.__str__("sreehari",10)

#Q2
class Calculator:
  def add(self,a,b):
    print(a+b)
  def sub(self,a,b):
    print(a-b)
  def mul(self,a,b):
    print(a*b)    
  def div(self,a,b):
    print(a/b)  
  def execute(self,func,a,b):
    if func=="add":
      self.add(a,b)
    elif func=="sub":
      self.sub(a,b)
    elif func=="mul":
      self.mul(a,b)    
    elif func=="div":
      self.div(a,b)  
    else: 
      print("Invalid Input")  

x=Calculator()
x.execute('mul',6,3)

