# -*- coding: utf-8 -*-
"""Function and Class Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N098jEHTu_xoQcUo9j6_a85zex_AvKlw
"""

#Q1
def factor(x):
  f=1
  for i in range(1,x+1):
    f=f*i
  return f
n=int(input("Enter a number:"))
print("Factorial:",factor(n))

#Q2
def check_string(s):
  i=0
  c=0
  while i<len(s):
    if s[i]=='s' or s[i]=='S':
      c+=1
    i+=1 
  if c>0:
    print("The string is containing the letter s")
  else:
    print("The string doesn't contain the letter s")

string=input("Enter String:")

check_string(string)

#Q3
class student:
  def fun1(self):
    x=input("enter value ")
    return x
  def message(self,x):
    self.x=x
    print(x)
  
obj=student()
x=obj.fun1()
obj.message(x)

#Q4
double_num=lambda a:a*2
print(double_num(10))

#Q5  
str1=input("Enter a string:")
if str1==str1[::-1]:
  print("String is Palindrome")
else:
  print("String is not Palindrome")